Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202404.26.0"

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|

      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "192.168.10.10#{i}"

      node.vm.provider "virtualbox" do |v|
        v.name = "node-#{i}"
        v.memory = 2048
        v.cpus = 2

        node.vm.provision "shell",
        inline: "echo hello from node #{i}"
      end
    end
  end
end
